---
# tasks file for grafana
- name: "Install gpg"
  apt:
    name: gnupg, software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: "add gpg key"
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: no

- name: "add repository"
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    validate_certs: no

- name: "install and update Grafana"
  apt:
    name: grafana
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: "Start service grafana-server"
  service:
    name: grafana-server
    enabled: true
    state: restarted

- name: "Check if Grafana is accessible"
  uri:
    url: http://127.0.0.1:3000
    method: GET
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1

- name: "Output Grafana"
  debug:
    msg: "Grafana is running. Connect from the Monitoring_Node to http://127.0.0.1:3000. Username: admin, Password: admin"
